# must have configs
n_clusters: 2
save_mode: 'save_png'

# encoder configs
n_components: 4
domain_size: 0.1963495

# classifier configs

# model configs
in_channels: 1
out_channels: 1
modes: 4
width: 20

# data configs
root: 'data/helmholtz'
partition: True
sub_size: 8
num_samples: 2000

# pred configs
idxs: [100]
timesteps: 1