# must have configs
n_clusters: 6
save_mode: 'save'

# encoder configs
n_components: 50
domain_size: 0.1963495

# classifier configs

# model configs
in_channels: 8
out_channels: 8
width: 64

# data configs
root: 'data/jhtdb_icml'
tstart: 1
tend: 500
fields: 'u'
dataset: 'isotropic1024coarse'
partition: True
sub_size: 32

# pred configs
idxs: [100, 200, 400]