# must have configs
n_clusters: 3
save_mode: 'save'

# encoder configs
n_components: 20
domain_size: 0.1963495

# classifier configs

# model configs
in_channels: 8
out_channels: 8
width: 20

# data configs
root: 'data/jhtdb_transition_bl'
tstart: 1
tend: 1000
fields: 'u'
dataset: 'transition_bl'
partition: True
sub_size: 8

# pred configs
idxs: [30]
timesteps: 20